# Generated by Django 5.1.15 on 2026-10-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entry_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('SECURITY', 'Security'), ('CRITICAL', 'Critical')], default='INFO', max_length=10),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['election', 'id'], name='core_auditl_electio_1791c4_idx'),
        ),
    ]
