# Generated by Django 5.1.15 on 2026-08-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
