# Generated by Django 5.1.15 on 2026-08-06 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otpverification_failed_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='core.organization'),
        ),
        migrations.CreateModel(
            name='ElectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('FACULTY', 'Faculty Election'), ('STATE_ASSOCIATION', 'State Association Election'), ('SUG', 'SUG Election')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_categories', to='core.organization')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='election',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='core.electioncategory'),
            preserve_default=False,
        ),
    ]
