# Generated by Django 5.1.15 on 2026-08-14 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stateassociationmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('invited_email', models.EmailField(blank=True, help_text='Email of the person this code was sent to', max_length=254)),
                ('invited_name', models.CharField(blank=True, help_text='Name of the person this code was sent to', max_length=200)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='core.organization')),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
